language: csharp
solution: Bantam.sln
before_install:
  - sudo apt-get install nunit-console
script:
  - xbuild /p:Configuration=Debug Bantam.sln
  - nunit-console BantamTest/bin/Debug/BantamTest.dll
